// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import FilterController from "./filter_controller"
import BarchartController from "./barchart_controller"
import DoughnutController from "./doughnut_controller"
import DoughnutChartController from "./doughnut_chart_controller"
import HorizontalbarController from "./horizontalbar_controller"
 
application.register("hello", HelloController)
application.register("filter", FilterController)
application.register("barchart", BarchartController)
application.register("doughnut", DoughnutController)
application.register("doughnut_chart", DoughnutChartController)
application.register("horizontalbar", HorizontalbarController)
 
